# action.yml
name: 'Ortus University TestBox Test Runner'
author: 'Ortus University'
description: 'Run CFML unit tests using CommandBox and TestBox'
inputs:
  cfml-engine:  # id of input
    description: 'The CFML engine to test and grade'
    required: true
    default: 'lucee@5'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.cfml-engine }}
branding:
  icon: 'award'
  color: 'green'